// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: PhysicsLab

#ifndef _PHYSICSLAB_UI_H
#define _PHYSICSLAB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_AQI_Meter;
extern lv_obj_t * ui_ColorPanel1;
extern lv_obj_t * ui_IMAGE1;
extern lv_obj_t * ui_KNOB1;
extern lv_obj_t * ui_AQI_TEXT;
extern lv_obj_t * ui_AQI_VALUE;
extern lv_obj_t * ui_CO2_Meter;
extern lv_obj_t * ui_ColorPanel2;
extern lv_obj_t * ui_IMAGE2;
extern lv_obj_t * ui_KNOB2;
extern lv_obj_t * ui_CO2_TEXT;
extern lv_obj_t * ui_CO2_VALUE;
extern lv_obj_t * ui_TEMPERATURE_METER;
extern lv_obj_t * ui_ColorPanel3;
extern lv_obj_t * ui_IMAGE3;
extern lv_obj_t * ui_KNOB3;
extern lv_obj_t * ui_TEMPERATURE_TEXT;
extern lv_obj_t * ui_Temp_Number;
extern lv_obj_t * ui_LETTER_C;
extern lv_obj_t * ui_DOT;
extern lv_obj_t * ui_TEMPERATURE_VALUE;
extern lv_obj_t * ui_HUMIDITY_METER;
extern lv_obj_t * ui_ColorPanel4;
extern lv_obj_t * ui_IMAGE4;
extern lv_obj_t * ui_KNOB4;
extern lv_obj_t * ui_HUMIDITY_TEXT;
extern lv_obj_t * ui_HUMIDITY_VALUE;
extern lv_obj_t * ui_Label;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_test99_png);    // assets/test99.png
LV_IMG_DECLARE(ui_img_zzzzzzz_png);    // assets/zzzzzzz.png
LV_IMG_DECLARE(ui_img_dot_png);    // assets/Dot.png
LV_IMG_DECLARE(ui_img_part1_png);    // assets/part1.png
LV_IMG_DECLARE(ui_img_part2_png);    // assets/part2.png
LV_IMG_DECLARE(ui_img_test22_png);    // assets/test22.png
LV_IMG_DECLARE(ui_img_test3_png);    // assets/test3.png

// FONTS
LV_FONT_DECLARE(ui_font_Text);
LV_FONT_DECLARE(ui_font_Text2);
LV_FONT_DECLARE(ui_font_Title);
LV_FONT_DECLARE(ui_font_Title2);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
