// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: PhysicsLab

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AQI_Meter = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_AQI_Meter);
    lv_obj_set_width(ui_AQI_Meter, 615);
    lv_obj_set_height(ui_AQI_Meter, 527);
    lv_obj_set_x(ui_AQI_Meter, -135);
    lv_obj_set_y(ui_AQI_Meter, -79);
    lv_obj_set_align(ui_AQI_Meter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AQI_Meter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ColorPanel1 = lv_obj_create(ui_AQI_Meter);
    lv_obj_set_width(ui_ColorPanel1, 133);
    lv_obj_set_height(ui_ColorPanel1, 99);
    lv_obj_set_x(ui_ColorPanel1, 60);
    lv_obj_set_y(ui_ColorPanel1, 38);
    lv_obj_set_align(ui_ColorPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ColorPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ColorPanel1, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorPanel1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMAGE1 = lv_arc_create(ui_AQI_Meter);
    lv_obj_set_width(ui_IMAGE1, 114);
    lv_obj_set_height(ui_IMAGE1, 132);
    lv_obj_set_x(ui_IMAGE1, 61);
    lv_obj_set_y(ui_IMAGE1, 64);
    lv_obj_set_align(ui_IMAGE1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_IMAGE1, 0, 200);
    lv_arc_set_value(ui_IMAGE1, 180);
    lv_obj_set_style_radius(ui_IMAGE1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IMAGE1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_IMAGE1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_IMAGE1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_IMAGE1, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_IMAGE1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_IMAGE1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_IMAGE1, &ui_img_test99_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_IMAGE1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_KNOB1 = lv_arc_create(ui_AQI_Meter);
    lv_obj_set_width(ui_KNOB1, 125);
    lv_obj_set_height(ui_KNOB1, 132);
    lv_obj_set_x(ui_KNOB1, 62);
    lv_obj_set_y(ui_KNOB1, 61);
    lv_obj_set_align(ui_KNOB1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_KNOB1, 0, 200);
    lv_arc_set_value(ui_KNOB1, 60);
    lv_arc_set_bg_angles(ui_KNOB1, 175, 5);
    lv_obj_set_style_radius(ui_KNOB1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KNOB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_KNOB1, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_KNOB1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB1, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_KNOB1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_KNOB1, lv_color_hex(0x00A2F4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KNOB1, &ui_img_zzzzzzz_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KNOB1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KNOB1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KNOB1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KNOB1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AQI_TEXT = lv_label_create(ui_AQI_Meter);
    lv_obj_set_width(ui_AQI_TEXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQI_TEXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQI_TEXT, 61);
    lv_obj_set_y(ui_AQI_TEXT, 70);
    lv_obj_set_align(ui_AQI_TEXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AQI_TEXT, "PM2.5");
    lv_obj_set_style_text_color(ui_AQI_TEXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQI_TEXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AQI_TEXT, &ui_font_Text, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQI_VALUE = lv_label_create(ui_AQI_Meter);
    lv_obj_set_width(ui_AQI_VALUE, lv_pct(10));
    lv_obj_set_height(ui_AQI_VALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQI_VALUE, 63);
    lv_obj_set_y(ui_AQI_VALUE, 40);
    lv_obj_set_align(ui_AQI_VALUE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AQI_VALUE, "000");
    lv_obj_set_style_text_color(ui_AQI_VALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQI_VALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AQI_VALUE, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2_Meter = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CO2_Meter);
    lv_obj_set_width(ui_CO2_Meter, 615);
    lv_obj_set_height(ui_CO2_Meter, 527);
    lv_obj_set_x(ui_CO2_Meter, 10);
    lv_obj_set_y(ui_CO2_Meter, -81);
    lv_obj_set_align(ui_CO2_Meter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2_Meter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ColorPanel2 = lv_obj_create(ui_CO2_Meter);
    lv_obj_set_width(ui_ColorPanel2, 133);
    lv_obj_set_height(ui_ColorPanel2, 99);
    lv_obj_set_x(ui_ColorPanel2, 61);
    lv_obj_set_y(ui_ColorPanel2, 41);
    lv_obj_set_align(ui_ColorPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ColorPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ColorPanel2, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorPanel2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMAGE2 = lv_arc_create(ui_CO2_Meter);
    lv_obj_set_width(ui_IMAGE2, 114);
    lv_obj_set_height(ui_IMAGE2, 132);
    lv_obj_set_x(ui_IMAGE2, 61);
    lv_obj_set_y(ui_IMAGE2, 64);
    lv_obj_set_align(ui_IMAGE2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_IMAGE2, 0, 200);
    lv_arc_set_value(ui_IMAGE2, 180);
    lv_obj_set_style_radius(ui_IMAGE2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IMAGE2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_IMAGE2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_IMAGE2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_IMAGE2, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_IMAGE2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_IMAGE2, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_IMAGE2, &ui_img_test99_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_IMAGE2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_KNOB2 = lv_arc_create(ui_CO2_Meter);
    lv_obj_set_width(ui_KNOB2, 125);
    lv_obj_set_height(ui_KNOB2, 132);
    lv_obj_set_x(ui_KNOB2, 62);
    lv_obj_set_y(ui_KNOB2, 61);
    lv_obj_set_align(ui_KNOB2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_KNOB2, 0, 200);
    lv_arc_set_value(ui_KNOB2, 180);
    lv_arc_set_bg_angles(ui_KNOB2, 175, 5);
    lv_obj_set_style_radius(ui_KNOB2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KNOB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_KNOB2, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_KNOB2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB2, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_KNOB2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_KNOB2, lv_color_hex(0x00A2F4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KNOB2, &ui_img_zzzzzzz_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KNOB2, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KNOB2, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KNOB2, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KNOB2, 10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CO2_TEXT = lv_label_create(ui_CO2_Meter);
    lv_obj_set_width(ui_CO2_TEXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2_TEXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2_TEXT, 63);
    lv_obj_set_y(ui_CO2_TEXT, 70);
    lv_obj_set_align(ui_CO2_TEXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2_TEXT, "CO2");
    lv_obj_set_style_text_color(ui_CO2_TEXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2_TEXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2_TEXT, &ui_font_Text, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2_VALUE = lv_label_create(ui_CO2_Meter);
    lv_obj_set_width(ui_CO2_VALUE, lv_pct(10));
    lv_obj_set_height(ui_CO2_VALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2_VALUE, 63);
    lv_obj_set_y(ui_CO2_VALUE, 40);
    lv_obj_set_align(ui_CO2_VALUE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2_VALUE, "000");
    lv_obj_set_style_text_color(ui_CO2_VALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2_VALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2_VALUE, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMPERATURE_METER = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_TEMPERATURE_METER);
    lv_obj_set_width(ui_TEMPERATURE_METER, 615);
    lv_obj_set_height(ui_TEMPERATURE_METER, 527);
    lv_obj_set_x(ui_TEMPERATURE_METER, -134);
    lv_obj_set_y(ui_TEMPERATURE_METER, 23);
    lv_obj_set_align(ui_TEMPERATURE_METER, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TEMPERATURE_METER, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ColorPanel3 = lv_obj_create(ui_TEMPERATURE_METER);
    lv_obj_set_width(ui_ColorPanel3, 133);
    lv_obj_set_height(ui_ColorPanel3, 99);
    lv_obj_set_x(ui_ColorPanel3, 60);
    lv_obj_set_y(ui_ColorPanel3, 41);
    lv_obj_set_align(ui_ColorPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ColorPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ColorPanel3, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorPanel3, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMAGE3 = lv_arc_create(ui_TEMPERATURE_METER);
    lv_obj_set_width(ui_IMAGE3, 114);
    lv_obj_set_height(ui_IMAGE3, 132);
    lv_obj_set_x(ui_IMAGE3, 61);
    lv_obj_set_y(ui_IMAGE3, 64);
    lv_obj_set_align(ui_IMAGE3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_IMAGE3, 0, 200);
    lv_arc_set_value(ui_IMAGE3, 180);
    lv_obj_set_style_radius(ui_IMAGE3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IMAGE3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_IMAGE3, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_IMAGE3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_IMAGE3, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_IMAGE3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_IMAGE3, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_IMAGE3, &ui_img_test99_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_IMAGE3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_KNOB3 = lv_arc_create(ui_TEMPERATURE_METER);
    lv_obj_set_width(ui_KNOB3, 125);
    lv_obj_set_height(ui_KNOB3, 132);
    lv_obj_set_x(ui_KNOB3, 62);
    lv_obj_set_y(ui_KNOB3, 61);
    lv_obj_set_align(ui_KNOB3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_KNOB3, 0, 200);
    lv_arc_set_value(ui_KNOB3, 0);
    lv_arc_set_bg_angles(ui_KNOB3, 175, 5);
    lv_obj_set_style_radius(ui_KNOB3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KNOB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB3, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_KNOB3, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_KNOB3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB3, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_KNOB3, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_KNOB3, lv_color_hex(0x00A2F4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KNOB3, &ui_img_zzzzzzz_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KNOB3, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KNOB3, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KNOB3, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KNOB3, 10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TEMPERATURE_TEXT = lv_label_create(ui_TEMPERATURE_METER);
    lv_obj_set_width(ui_TEMPERATURE_TEXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMPERATURE_TEXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPERATURE_TEXT, 63);
    lv_obj_set_y(ui_TEMPERATURE_TEXT, 73);
    lv_obj_set_align(ui_TEMPERATURE_TEXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMPERATURE_TEXT, "Temperature");
    lv_obj_set_style_text_color(ui_TEMPERATURE_TEXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TEMPERATURE_TEXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TEMPERATURE_TEXT, &ui_font_Text2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp_Number = lv_obj_create(ui_TEMPERATURE_METER);
    lv_obj_remove_style_all(ui_Temp_Number);
    lv_obj_set_width(ui_Temp_Number, 268);
    lv_obj_set_height(ui_Temp_Number, 218);
    lv_obj_set_x(ui_Temp_Number, 77);
    lv_obj_set_y(ui_Temp_Number, 24);
    lv_obj_set_align(ui_Temp_Number, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temp_Number, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LETTER_C = lv_label_create(ui_Temp_Number);
    lv_obj_set_width(ui_LETTER_C, lv_pct(10));
    lv_obj_set_height(ui_LETTER_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LETTER_C, 11);
    lv_obj_set_y(ui_LETTER_C, 17);
    lv_obj_set_align(ui_LETTER_C, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LETTER_C, "C");
    lv_obj_set_style_text_color(ui_LETTER_C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LETTER_C, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LETTER_C, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DOT = lv_img_create(ui_Temp_Number);
    lv_img_set_src(ui_DOT, &ui_img_dot_png);
    lv_obj_set_width(ui_DOT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DOT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DOT, -6);
    lv_obj_set_y(ui_DOT, 2);
    lv_obj_set_align(ui_DOT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DOT, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DOT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TEMPERATURE_VALUE = lv_label_create(ui_Temp_Number);
    lv_obj_set_width(ui_TEMPERATURE_VALUE, lv_pct(15));
    lv_obj_set_height(ui_TEMPERATURE_VALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPERATURE_VALUE, -27);
    lv_obj_set_y(ui_TEMPERATURE_VALUE, 17);
    lv_obj_set_align(ui_TEMPERATURE_VALUE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMPERATURE_VALUE, "00");
    lv_obj_set_style_text_color(ui_TEMPERATURE_VALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TEMPERATURE_VALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TEMPERATURE_VALUE, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HUMIDITY_METER = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_HUMIDITY_METER);
    lv_obj_set_width(ui_HUMIDITY_METER, 615);
    lv_obj_set_height(ui_HUMIDITY_METER, 527);
    lv_obj_set_x(ui_HUMIDITY_METER, 10);
    lv_obj_set_y(ui_HUMIDITY_METER, 23);
    lv_obj_set_align(ui_HUMIDITY_METER, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HUMIDITY_METER, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ColorPanel4 = lv_obj_create(ui_HUMIDITY_METER);
    lv_obj_set_width(ui_ColorPanel4, 133);
    lv_obj_set_height(ui_ColorPanel4, 99);
    lv_obj_set_x(ui_ColorPanel4, 62);
    lv_obj_set_y(ui_ColorPanel4, 40);
    lv_obj_set_align(ui_ColorPanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ColorPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ColorPanel4, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorPanel4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMAGE4 = lv_arc_create(ui_HUMIDITY_METER);
    lv_obj_set_width(ui_IMAGE4, 114);
    lv_obj_set_height(ui_IMAGE4, 132);
    lv_obj_set_x(ui_IMAGE4, 61);
    lv_obj_set_y(ui_IMAGE4, 64);
    lv_obj_set_align(ui_IMAGE4, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_IMAGE4, 0, 200);
    lv_arc_set_value(ui_IMAGE4, 180);
    lv_obj_set_style_radius(ui_IMAGE4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IMAGE4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_IMAGE4, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_IMAGE4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_IMAGE4, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_IMAGE4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_IMAGE4, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_IMAGE4, &ui_img_test99_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_IMAGE4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMAGE4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_KNOB4 = lv_arc_create(ui_HUMIDITY_METER);
    lv_obj_set_width(ui_KNOB4, 125);
    lv_obj_set_height(ui_KNOB4, 132);
    lv_obj_set_x(ui_KNOB4, 62);
    lv_obj_set_y(ui_KNOB4, 61);
    lv_obj_set_align(ui_KNOB4, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_KNOB4, 0, 200);
    lv_arc_set_value(ui_KNOB4, 200);
    lv_arc_set_bg_angles(ui_KNOB4, 175, 5);
    lv_obj_set_style_radius(ui_KNOB4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KNOB4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB4, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_KNOB4, lv_color_hex(0x931616), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_KNOB4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_KNOB4, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_KNOB4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_KNOB4, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_KNOB4, lv_color_hex(0x00A2F4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KNOB4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KNOB4, &ui_img_zzzzzzz_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KNOB4, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KNOB4, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KNOB4, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KNOB4, 10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HUMIDITY_TEXT = lv_label_create(ui_HUMIDITY_METER);
    lv_obj_set_width(ui_HUMIDITY_TEXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HUMIDITY_TEXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HUMIDITY_TEXT, 63);
    lv_obj_set_y(ui_HUMIDITY_TEXT, 69);
    lv_obj_set_align(ui_HUMIDITY_TEXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HUMIDITY_TEXT, "HUMIDITY");
    lv_obj_set_style_text_color(ui_HUMIDITY_TEXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HUMIDITY_TEXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HUMIDITY_TEXT, &ui_font_Text2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HUMIDITY_VALUE = lv_label_create(ui_HUMIDITY_METER);
    lv_obj_set_width(ui_HUMIDITY_VALUE, lv_pct(10));
    lv_obj_set_height(ui_HUMIDITY_VALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HUMIDITY_VALUE, 63);
    lv_obj_set_y(ui_HUMIDITY_VALUE, 40);
    lv_obj_set_align(ui_HUMIDITY_VALUE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HUMIDITY_VALUE, "000");
    lv_obj_set_style_text_color(ui_HUMIDITY_VALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HUMIDITY_VALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HUMIDITY_VALUE, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Label);
    lv_obj_set_width(ui_Label, 347);
    lv_obj_set_height(ui_Label, 374);
    lv_obj_set_align(ui_Label, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Label);
    lv_obj_set_width(ui_Panel1, 160);
    lv_obj_set_height(ui_Panel1, 43);
    lv_obj_set_x(ui_Panel1, 4);
    lv_obj_set_y(ui_Panel1, -116);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x344955), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Label);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 4);
    lv_obj_set_y(ui_Label1, -110);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Air Quality Status");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Title2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
